// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivfkfkoiwiwiycxaztci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2Zmtma29pd2l3aXljeGF6dGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NzE2NDQsImV4cCI6MjA2MDQ0NzY0NH0.9VEnk1wUE3z8NiIkSgyPtRfi9ACvQ-0-BkB5NQ2gdDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);